// src/app/api/local-builder/deploy/route.ts
import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs/promises";

type BuildType = "app" | "agent" | "dashboard" | "workflow";

interface DeployStep {
  id: string;
  label: string;
  detail: string;
}

interface DeployPlan {
  targetEnv: string;
  steps: DeployStep[];
  summary: string;
}

interface DeployRequestBody {
  projectId: string;
  title?: string;
  buildType?: BuildType;
}

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true });
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as DeployRequestBody;

    if (!body?.projectId) {
      return NextResponse.json(
        { ok: false, error: "Missing projectId in request body." },
        { status: 400 }
      );
    }

    const projectIdSafe = body.projectId.replace(/[^a-zA-Z0-9_-]/g, "_");
    const rootDir = path.join(process.cwd(), "generated-local", projectIdSafe);

    // Folders for deploy artifacts
    const deployDir = path.join(rootDir, "deploy");
    const githubDir = path.join(rootDir, ".github");
    const workflowsDir = path.join(githubDir, "workflows");

    await ensureDir(deployDir);
    await ensureDir(workflowsDir);

    // vercel.json (basic Next.js config)
    const vercelJsonPath = path.join(deployDir, "vercel.json");
    const vercelJson = `{
  "version": 2,
  "builds": [
    { "src": "package.json", "use": "@vercel/next" }
  ],
  "env": {
    "NODE_ENV": "production"
  }
}
`;
    await fs.writeFile(vercelJsonPath, vercelJson, "utf8");

    // GitHub Actions workflow for Vercel deploy (manual-friendly)
    const workflowPath = path.join(workflowsDir, "vercel-deploy.yml");
    // Helper to generate GitHub Actions secret reference syntax
    const secretRef = (name: string): string => {
      return "${{ secrets." + name + " }}";
    };
    const workflow = `# Auto-generated by Zero17 Builder Lab
# GitHub Actions workflow for deploying to Vercel.
# You must set the following secrets in your GitHub repo:
#   - VERCEL_TOKEN
#   - VERCEL_ORG_ID
#   - VERCEL_PROJECT_ID

name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${secretRef("VERCEL_TOKEN")}
        env:
          VERCEL_ORG_ID: ${secretRef("VERCEL_ORG_ID")}
          VERCEL_PROJECT_ID: ${secretRef("VERCEL_PROJECT_ID")}
`;
    await fs.writeFile(workflowPath, workflow, "utf8");

    // DEPLOY-STEPS.md with a clear checklist
    const deployStepsPath = path.join(deployDir, "DEPLOY-STEPS.md");
    const deployTitle = body.title || "Zero17 Build";
    const buildType = body.buildType || "app";

    const deployStepsMd = `# Zero17 Deploy Blueprint

Project: ${deployTitle}
Type: ${buildType}
Project ID: ${body.projectId}

This blueprint assumes a Vercel + GitHub deployment with a Next.js app.

---

## Step 1 – Create a GitHub repo

1. Create a new repo on GitHub (public or private).
2. Copy the contents of this generated folder into the repo root:
   - app/
   - lib/
   - db/
   - agents/
   - tests/
   - deploy/
   - ZERO17-GENERATED.md
3. Add a basic package.json or reuse your existing monorepo tooling.

---

## Step 2 – Install dependencies

In your repo:

\`\`\`bash
npm init -y                # if you don't have package.json yet
npm install next react react-dom
npm install --save-dev typescript @types/react @types/node
npm install --save-dev jest @types/jest ts-node @playwright/test
\`\`\`

Set up the usual Next.js scripts:

\`\`\`jsonc
// package.json
{
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "jest --config ./tests/jest.config.mjs",
    "test:e2e": "playwright test --config ./tests/playwright.config.ts"
  }
}
\`\`\`

---

## Step 3 – Connect repo to Vercel

1. Go to Vercel and create a new project from your GitHub repo.
2. Select the framework preset: **Next.js**.
3. Set your build command and output (Vercel will infer these automatically in most cases).
4. Optional: set any environment variables required by your app.

---

## Step 4 – Configure GitHub Actions (optional)

1. Push the repo to GitHub.
2. Ensure the following secrets are defined in your repo settings:
   - \`VERCEL_TOKEN\`
   - \`VERCEL_ORG_ID\`
   - \`VERCEL_PROJECT_ID\`
3. The workflow in \`.github/workflows/vercel-deploy.yml\` will:
   - Run on every push to \`main\`
   - Or on manual trigger via "Run workflow"
   - Build and deploy your app to Vercel.

---

## Step 5 – Local smoke test before first deploy

1. Run dev server:

\`\`\`bash
npm run dev
\`\`\`

2. In another terminal, run tests:

\`\`\`bash
npm test         # Jest smoke tests
npm run test:e2e # Playwright smoke tests
\`\`\`

Fix any issues before shipping to production.

---

## Step 6 – First production deploy

Either:

- Push to \`main\` and let GitHub Actions + Vercel handle it.
- Or trigger a "Deploy" manually from the Vercel UI.

Once deployed, treat this as your v0. Ship quickly, then iterate.
`;

    await fs.writeFile(deployStepsPath, deployStepsMd, "utf8");

    const steps: DeployStep[] = [
      {
        id: "repo",
        label: "Create GitHub repo",
        detail:
          "Create a new GitHub repo and copy the generated app/, lib/, db/, agents/, tests/, and deploy/ folders into it.",
      },
      {
        id: "deps",
        label: "Install dependencies",
        detail:
          "Install Next.js, React, TypeScript, Jest, and Playwright in the repo. Add dev/build/test scripts to package.json.",
      },
      {
        id: "vercel_link",
        label: "Link repo to Vercel",
        detail:
          "Create a new Vercel project from the GitHub repo, using the Next.js preset. Configure any required env vars.",
      },
      {
        id: "gha_setup",
        label: "Configure GitHub Actions (optional)",
        detail:
          "Set VERCEL_TOKEN, VERCEL_ORG_ID, and VERCEL_PROJECT_ID secrets. The vercel-deploy.yml workflow will handle CI/CD.",
      },
      {
        id: "smoke_tests",
        label: "Run smoke tests locally",
        detail:
          "Run `npm test` and `npm run test:e2e` using the generated Jest and Playwright configs before your first production deploy.",
      },
      {
        id: "first_deploy",
        label: "Ship v0 to production",
        detail:
          "Push to main or trigger a manual deploy from Vercel to ship your first production version.",
      },
    ];

    const plan: DeployPlan = {
      targetEnv: "Vercel + GitHub",
      steps,
      summary:
        "This deploy blueprint wires your generated build into a Vercel + GitHub flow: repo → tests → CI → production deploy. Start simple, then layer more checks as the product matures.",
    };

    return NextResponse.json({ ok: true, plan });
  } catch (err: any) {
    console.error("[local-builder:deploy] error", err);
    return NextResponse.json(
      {
        ok: false,
        error: err?.message || "Unexpected error in deploy route.",
      },
      { status: 500 }
    );
  }
}
