import { NextResponse } from "next/server";
import type { BuilderProject } from "@/lib/builder/types";
import { loadProjectOrRes } from "@/app/api/builder/_project";

type PostBody = { projectId: string };

type DocsPack = {
  summary: string;
  readme: string;
  architectureNotes: string;
  runbook: string;
  clientPack: string;
};

function safeJson(x: any) {
  try {
    return JSON.stringify(x ?? null, null, 2);
  } catch {
    return "null";
  }
}

function buildDocsPack(project: BuilderProject): DocsPack {
  const title = project.title || "Zero17 Project";
  const kind = project.kind ?? "app";
  const status = project.status ?? "draft";

  return {
    summary: `Docs pack generated for ${title} (${kind}). Status: ${status}.`,
    readme: `# ${title}

## What this is
Generated by Zero17 Builder Lab.

## How to run
- npm i
- npm run dev

## Artifacts
- spec_json: ${project.spec_json ? "present" : "missing"}
- architecture_json: ${project.architecture_json ? "present" : "missing"}
- export_plan_json: ${project.export_plan_json ? "present" : "missing"}
- test_plan_json: ${project.test_plan_json ? "present" : "missing"}
- deployment_plan_json: ${project.deployment_plan_json ? "present" : "missing"}
- scan_report_json: ${project.scan_report_json ? "present" : "missing"}
- diagnostics_json: ${project.diagnostics_json ? "present" : "missing"}
`,
    architectureNotes: `## Architecture Notes
kind: ${kind}
status: ${status}

### architecture_json
${project.architecture_json ? safeJson(project.architecture_json) : "No architecture yet."}

### Latest Scan
${project.scan_report_json ? safeJson(project.scan_report_json) : "No scan yet."}
`,
    runbook: `## Runbook
1) Deploy Plan → set env vars → deploy
2) Smoke test: /builder, create project, run tests, scan
3) Generate Docs + Diagnostics
`,
    clientPack: `## Client Delivery Pack
- Spec + Architecture JSON
- Test plan + Scan report
- Docs pack + Diagnostics
- Deploy blueprint
`,
  };
}

export async function POST(req: Request) {
  const body = (await req.json().catch(() => null)) as PostBody | null;
  if (!body?.projectId)
    return NextResponse.json({ error: "Missing projectId" }, { status: 400 });

  const loaded = await loadProjectOrRes({
    projectId: body.projectId,
    caller: "POST /api/builder/docs",
  });
  if (loaded.res) return loaded.res;

  const { project, userId, supabase } = loaded;

  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const docsPack = buildDocsPack(project);

  const { data: updated, error } = await supabase
    .from("builder_projects")
    .update({
      docs_pack_json: docsPack,
      status: "docs_ready",
      updated_at: new Date().toISOString(),
    })
    .eq("id", project.id)
    .eq("user_id", userId)
    .select("*")
    .single();

  if (error || !updated) {
    console.error("[POST /api/builder/docs] update error:", error);
    return NextResponse.json(
      { error: "Failed to save docs", details: error?.message },
      { status: 500 }
    );
  }

  return NextResponse.json({ project: updated, docsPack }, { status: 200 });
}
