import { NextResponse } from "next/server";
import type { BuilderProject } from "@/lib/builder/types";
import {
  requireUserOrDemo,
  getProjectOrThrow,
} from "@/app/api/builder/_shared";

type PostBody = { projectId: string };

type SimpleDocsPack = {
  summary: string;
  readme: string;
  architectureNotes: string;
  runbook: string;
  clientPack: string;
};

function safeJson(x: any) {
  try {
    return JSON.stringify(x ?? null, null, 2);
  } catch {
    return "null";
  }
}

function buildDocs(project: BuilderProject): SimpleDocsPack {
  const title = project.title;

  const readme = `# ${title}

## What this is
Generated by Zero17 Builder Lab.

## How to run
- npm i
- npm run dev

## Builder artifacts
- spec_json: ${project.spec_json ? "present" : "missing"}
- architecture_json: ${project.architecture_json ? "present" : "missing"}
- export_plan_json: ${project.export_plan_json ? "present" : "missing"}
- test_plan_json: ${project.test_plan_json ? "present" : "missing"}
- deployment_plan_json: ${project.deployment_plan_json ? "present" : "missing"}
- scan_report_json: ${project.scan_report_json ? "present" : "missing"}
- docs_pack_json: present
- diagnostics_json: ${project.diagnostics_json ? "present" : "missing"}
`;

  const architectureNotes = `## Architecture Notes
kind: ${project.kind ?? "app"}
status: ${project.status}

### architecture_json
${project.architecture_json ? safeJson(project.architecture_json) : "No architecture yet."}

### Latest Scan (Phase 7)
${project.scan_report_json ? safeJson(project.scan_report_json) : "No scan yet."}
`;

  const runbook = `## Runbook
- Deploy: run deploy blueprint, set env vars, deploy Vercel, smoke test
- Smoke: create project, run tests, run scan, generate docs, run diagnostics
`;

  const clientPack = `## Client Pack
- Spec + Architecture JSON
- Test plan + Scan report
- Docs pack + Diagnostics
- Deploy blueprint
`;

  return {
    summary: `Docs pack generated for ${title}.`,
    readme,
    architectureNotes,
    runbook,
    clientPack,
  };
}

export async function POST(req: Request) {
  const { supabase, userId } = await requireUserOrDemo();

  let body: PostBody;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  if (!body.projectId)
    return NextResponse.json({ error: "Missing projectId" }, { status: 400 });

  const loaded = await getProjectOrThrow({
    supabase,
    projectId: body.projectId,
    userId,
    caller: "POST /api/builder/docs",
  });
  if (loaded.res) return loaded.res;

  const docs = buildDocs(loaded.project as BuilderProject);

  const { data: updated, error: updateErr } = await supabase
    .from("builder_projects")
    .update({ docs_pack_json: docs, status: "docs_ready" })
    .eq("id", body.projectId)
    .eq("user_id", userId)
    .select("*")
    .single();

  if (updateErr) {
    console.error("[POST /api/builder/docs] update error:", updateErr);
    return NextResponse.json({ error: "Failed to save docs" }, { status: 500 });
  }

  return NextResponse.json({ project: updated }, { status: 200 });
}
