// src/app/api/local-builder/tests/route.ts
import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs/promises";

type BuildType = "app" | "agent" | "dashboard" | "workflow";

type TestCaseStatus = "pass" | "fail";

interface TestCase {
  id: string;
  title: string;
  status: TestCaseStatus;
  detail: string;
}

interface TestReport {
  total: number;
  passed: number;
  failed: number;
  cases: TestCase[];
}

interface TestRequestBody {
  projectId: string;
  title?: string;
  buildType?: BuildType;
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true });
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as TestRequestBody;

    if (!body?.projectId) {
      return NextResponse.json(
        { ok: false, error: "Missing projectId in request body." },
        { status: 400 }
      );
    }

    const projectIdSafe = body.projectId.replace(/[^a-zA-Z0-9_-]/g, "_");
    const rootDir = path.join(process.cwd(), "generated-local", projectIdSafe);

    const rootExists = await pathExists(rootDir);
    if (!rootExists) {
      const report: TestReport = {
        total: 1,
        passed: 0,
        failed: 1,
        cases: [
          {
            id: "root_missing",
            title: "Generated build folder exists",
            status: "fail",
            detail: `Folder ${rootDir} does not exist. Run "Generate app" in Builder Lab first.`,
          },
        ],
      };
      return NextResponse.json({ ok: true, report });
    }

    // Important files we expect from codegen
    const expectedFiles = [
      {
        id: "app_page",
        relPath: "app/page.tsx",
        label: "Next.js app shell exists",
      },
      {
        id: "schema_ts",
        relPath: "lib/schema.ts",
        label: "Schema config exists",
      },
      {
        id: "agents_ts",
        relPath: "lib/agents.ts",
        label: "Agents config exists",
      },
      { id: "db_schema", relPath: "db/schema.sql", label: "DB schema exists" },
      {
        id: "agent_runtime",
        relPath: "agents/runtime.ts",
        label: "Agent runtime config exists",
      },
    ];

    const cases: TestCase[] = [];

    for (const f of expectedFiles) {
      const fullPath = path.join(rootDir, f.relPath);
      const exists = await pathExists(fullPath);
      cases.push({
        id: f.id,
        title: f.label,
        status: exists ? "pass" : "fail",
        detail: exists
          ? `Found ${f.relPath}.`
          : `Missing ${f.relPath}. Re-run codegen or check the codegen route.`,
      });
    }

    // Scaffold Jest + Playwright into /tests
    const testsDir = path.join(rootDir, "tests");
    await ensureDir(testsDir);

    const jestConfigPath = path.join(testsDir, "jest.config.mjs");
    const jestConfig = `// Auto-generated by Zero17 Builder Lab
// Drop this into your Jest setup or move it to the repo root.

export default {
  testEnvironment: "node",
  testMatch: ["**/*.test.[jt]s?(x)"],
  transform: {},
};
`;
    await fs.writeFile(jestConfigPath, jestConfig, "utf8");

    const jestSmokePath = path.join(testsDir, "smoke.generated.test.ts");
    const jestSmoke = `// Auto-generated by Zero17 Builder Lab
// Basic smoke tests for the generated build.

import fs from "fs";
import path from "path";

function resolved(p: string) {
  return path.join(__dirname, "..", p);
}

describe("Zero17 generated build smoke", () => {
  it("has app/page.tsx", () => {
    const filePath = resolved("app/page.tsx");
    expect(fs.existsSync(filePath)).toBe(true);
  });

  it("has lib/schema.ts", () => {
    const filePath = resolved("lib/schema.ts");
    expect(fs.existsSync(filePath)).toBe(true);
  });

  it("has lib/agents.ts", () => {
    const filePath = resolved("lib/agents.ts");
    expect(fs.existsSync(filePath)).toBe(true);
  });

  it("has db/schema.sql", () => {
    const filePath = resolved("db/schema.sql");
    expect(fs.existsSync(filePath)).toBe(true);
  });

  it("has agents/runtime.ts", () => {
    const filePath = resolved("agents/runtime.ts");
    expect(fs.existsSync(filePath)).toBe(true);
  });
});
`;
    await fs.writeFile(jestSmokePath, jestSmoke, "utf8");

    const playwrightConfigPath = path.join(testsDir, "playwright.config.ts");
    const playwrightConfig = `// Auto-generated by Zero17 Builder Lab
// Opinionated Playwright config for the generated Next.js app.
//
// Usage:
//   npx playwright test --config ./tests/playwright.config.ts

import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: __dirname,
  use: {
    baseURL: "http://localhost:3000",
    trace: "on-first-retry",
    headless: true,
  },
  reporter: [["list"]],
});
`;
    await fs.writeFile(playwrightConfigPath, playwrightConfig, "utf8");

    const playwrightSpecPath = path.join(testsDir, "e2e.smoke.spec.ts");
    const playwrightSpec = `// Auto-generated by Zero17 Builder Lab
// Minimal Playwright smoke test for the generated app shell.

import { test, expect } from "@playwright/test";

test("generated app loads root page", async ({ page }) => {
  await page.goto("/");
  await expect(page).toHaveTitle(/Zero17/i);
});
`;
    await fs.writeFile(playwrightSpecPath, playwrightSpec, "utf8");

    const testsReadmePath = path.join(testsDir, "README.md");
    const testsReadme = `# Zero17 Test Scaffolding

This folder was created by Zero17 Builder Lab for project:
- ID: ${body.projectId}
${body.title ? `- Title: ${body.title}\n` : ""}

It contains:

- jest.config.mjs
- smoke.generated.test.ts
- playwright.config.ts
- e2e.smoke.spec.ts

## How to run

1. Make sure your generated app is in a standalone repo or workspace.
2. Install test dependencies:

   npm install --save-dev jest @types/jest ts-node typescript @playwright/test

3. Run Jest smoke tests:

   npx jest --config ./tests/jest.config.mjs

4. Run Playwright smoke tests:

   npx playwright test --config ./tests/playwright.config.ts

Adapt these to your existing tooling as needed.
`;
    await fs.writeFile(testsReadmePath, testsReadme, "utf8");

    cases.push({
      id: "jest_scaffold",
      title: "Jest scaffold generated",
      status: "pass",
      detail: "Jest config + smoke test written to /tests.",
    });
    cases.push({
      id: "playwright_scaffold",
      title: "Playwright scaffold generated",
      status: "pass",
      detail: "Playwright config + e2e smoke spec written to /tests.",
    });

    const passed = cases.filter((c) => c.status === "pass").length;
    const failed = cases.filter((c) => c.status === "fail").length;

    const report: TestReport = {
      total: cases.length,
      passed,
      failed,
      cases,
    };

    return NextResponse.json({ ok: true, report });
  } catch (err: any) {
    console.error("[local-builder:tests] error", err);
    return NextResponse.json(
      {
        ok: false,
        error: err?.message || "Unexpected error in tests route.",
      },
      { status: 500 }
    );
  }
}
