// src/lib/local-builder/codegen.ts

import * as fs from "fs/promises";
import * as path from "path";

export type LocalBuildType = "app" | "agent" | "dashboard" | "workflow";

export interface LocalArchitectureEntity {
  id?: string;
  name?: string;
  description?: string;
  kind?: "data" | "service" | "external";
  notes?: string;
}

export interface LocalAgentDefinition {
  id?: string;
  name?: string;
  mission?: string;
  persona?: string;
  tools?: string;
  handoffs?: string;
}

export interface LocalBuilderProject {
  id: string;
  title: string;
  description?: string;
  buildType: LocalBuildType;
  architecture?: LocalArchitectureEntity[];
  agents?: LocalAgentDefinition[];
}

export interface LocalCodegenResult {
  rootDir: string;
  files: string[];
}

/**
 * Generate a minimal but real Next.js app scaffold for this project ID
 * under /generated-local/{projectId}, including:
 * - app shell
 * - schema.ts from architecture
 * - agents.ts from agent employees
 */
export async function generateLocalNextApp(
  project: LocalBuilderProject
): Promise<LocalCodegenResult> {
  const rootDir = path.join(process.cwd(), "generated-local", project.id);

  // Clean previous build
  await fs.rm(rootDir, { recursive: true, force: true });

  const appDir = path.join(rootDir, "app");
  const libDir = path.join(rootDir, "lib");
  await fs.mkdir(appDir, { recursive: true });
  await fs.mkdir(libDir, { recursive: true });

  const title = project.title || "Zero17 Builder Project";
  const description =
    project.description ||
    `Generated ${project.buildType} scaffold by Zero17 Builder Lab.`;

  /* ------------------------------------------------------------------------ */
  /*  Normalize architecture + agents                                         */
  /* ------------------------------------------------------------------------ */

  const normalizedEntities = (project.architecture ?? [])
    .filter((e) => (e.name ?? "").trim() !== "")
    .map((e) => ({
      name: (e.name ?? "Unnamed entity").trim(),
      kind: (e.kind ?? "data") as "data" | "service" | "external",
      description: (e.description ?? "").trim(),
      notes: (e.notes ?? "").trim(),
    }));

  const normalizedAgents = (project.agents ?? [])
    .filter((a) => (a.name ?? "").trim() !== "")
    .map((a) => ({
      name: (a.name ?? "Unnamed agent").trim(),
      mission: (a.mission ?? "").trim(),
      persona: (a.persona ?? "").trim(),
      tools: (a.tools ?? "").trim(),
      handoffs: (a.handoffs ?? "").trim(),
    }));

  const entitiesJson = JSON.stringify(normalizedEntities, null, 2);
  const agentsJson = JSON.stringify(normalizedAgents, null, 2);

  const entitiesLiteral = entitiesJson === "[]" ? "[]" : entitiesJson;
  const agentsLiteral = agentsJson === "[]" ? "[]" : agentsJson;

  /* ------------------------------------------------------------------------ */
  /*  layout.tsx                                                              */
  /* ------------------------------------------------------------------------ */

  const layoutTsx = `import "./globals.css";
import type { ReactNode } from "react";

export const metadata = {
  title: "${title.replace(/"/g, "'")}",
  description: "${description.replace(/"/g, "'")}",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-slate-950 text-slate-50">
        <div className="mx-auto flex min-h-screen max-w-5xl flex-col px-4 py-6">
          <header className="mb-6 flex items-center justify-between gap-4 border-b border-slate-800 pb-4">
            <div>
              <h1 className="text-xl font-semibold tracking-tight">${title}</h1>
              <p className="mt-1 text-xs text-slate-400">
                ${description.replace(/"/g, "'")}
              </p>
            </div>
            <span className="rounded-full border border-emerald-500/40 bg-emerald-900/20 px-3 py-1 text-[10px] font-medium text-emerald-200">
              Generated by Zero17 · Builder Lab
            </span>
          </header>
          <main className="flex-1">{children}</main>
          <footer className="mt-6 border-t border-slate-900 pt-3 text-[10px] text-slate-500">
            Zero17 · Local build scaffold. Extend, refactor, and own it.
          </footer>
        </div>
      </body>
    </html>
  );
}
`;

  /* ------------------------------------------------------------------------ */
  /*  page.tsx                                                                */
  /* ------------------------------------------------------------------------ */

  const pageTsx = `import { entities, dataEntities, serviceEntities, externalEntities } from "../lib/schema";
import { agents } from "../lib/agents";

export default function Page() {
  return (
    <div className="space-y-4">
      <section className="rounded-2xl border border-slate-800 bg-slate-950/80 p-4">
        <h2 className="text-sm font-semibold text-slate-50">Command Deck</h2>
        <p className="mt-1 text-xs text-slate-400">
          This is the entry screen for <span className="font-semibold">${title}</span>.
          Generated by Zero17 Builder Lab for local development.
        </p>
        <ul className="mt-3 space-y-1 text-xs text-slate-300">
          <li>• Tech: Next.js App Router + Tailwind-ready shell.</li>
          <li>• Schema + agents are wired as typed configs under <code className="px-1 py-0.5 rounded bg-slate-900 border border-slate-700 text-[10px]">lib/schema.ts</code> and <code className="px-1 py-0.5 rounded bg-slate-900 border border-slate-700 text-[10px]">lib/agents.ts</code>.</li>
          <li>• This shell is meant to be refactored into your real app architecture.</li>
        </ul>
      </section>

      <section className="grid gap-3 md:grid-cols-3">
        <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-3">
          <p className="text-[11px] font-semibold text-slate-100">Build type</p>
          <p className="mt-1 text-[11px] text-slate-300">${project.buildType.toUpperCase()}</p>
        </div>
        <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-3">
          <p className="text-[11px] font-semibold text-slate-100">Entities</p>
          <p className="mt-1 text-[11px] text-slate-300">
            {entities.length} total · {dataEntities.length} data · {serviceEntities.length} services · {externalEntities.length} external.
          </p>
        </div>
        <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-3">
          <p className="text-[11px] font-semibold text-slate-100">Agent employees</p>
          <p className="mt-1 text-[11px] text-slate-300">
            {agents.length === 0 ? "No agents defined yet." : agents.length === 1 ? "1 agent" : agents.length + " agents"} ready to be wired into your runtime.
          </p>
        </div>
      </section>
    </div>
  );
}
`;

  /* ------------------------------------------------------------------------ */
  /*  globals.css                                                             */
  /* ------------------------------------------------------------------------ */

  const globalsCss = `:root {
  color-scheme: dark;
}
body {
  margin: 0;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif;
}
`;

  /* ------------------------------------------------------------------------ */
  /*  schema.ts from architecture                                             */
  /* ------------------------------------------------------------------------ */

  const schemaTs = `// Auto-generated by Zero17 Builder Lab
// Source: Builder → Architecture (entities & services)

export type EntityKind = "data" | "service" | "external";

export interface EntitySpec {
  name: string;
  kind: EntityKind;
  description: string;
  notes?: string;
}

export const entities: EntitySpec[] = ${entitiesLiteral};

export const dataEntities = entities.filter((e) => e.kind === "data");
export const serviceEntities = entities.filter((e) => e.kind === "service");
export const externalEntities = entities.filter((e) => e.kind === "external");

/**
 * Suggested use:
 * - Map dataEntities to actual tables/collections.
 * - Map serviceEntities to modules/functions or microservices.
 * - Map externalEntities to integration clients (Stripe, Slack, etc).
 *
 * This file is intentionally simple: it is the bridge between Builder Lab's
 * architecture UI and real schema/infra code in your app.
 */
`;

  /* ------------------------------------------------------------------------ */
  /*  agents.ts from agent employees                                          */
  /* ------------------------------------------------------------------------ */

  const agentsTs = `// Auto-generated by Zero17 Builder Lab
// Source: Builder → Agent employees

export interface AgentConfig {
  name: string;
  mission: string;
  persona: string;
  tools: string;
  handoffs: string;
}

export const agents: AgentConfig[] = ${agentsLiteral};

/**
 * Suggested use:
 * - Use AgentConfig as the source of truth for your agent runtime configs.
 * - Map "tools" to actual tool/router definitions (e.g. LangGraph / custom tools).
 * - Parse "handoffs" into graph edges or routing logic.
 */

export function findAgentByName(name: string): AgentConfig | undefined {
  return agents.find(
    (a) => a.name.toLowerCase() === name.trim().toLowerCase()
  );
}
`;

  /* ------------------------------------------------------------------------ */
  /*  README                                                                  */
  /* ------------------------------------------------------------------------ */

  const readme = `# ${title}

Generated by **Zero17 · Builder Lab** (local mode).

- Build type: \`${project.buildType}\`
- Generated at: ${new Date().toISOString()}
- Path: \`/generated-local/${project.id}\`

## What you get

- Next.js App Router structure
- Tailwind-ready layout + shell (configure Tailwind in your host app)
- A simple Command Deck page
- \`lib/schema.ts\` derived from Builder architecture (entities & services)
- \`lib/agents.ts\` derived from Builder agent employees

## How to use

1. Create a new Next.js app, or use an existing one.
2. Copy the contents of \`/generated-local/${project.id}/app\` into your app's \`app/\` folder (or a route group).
3. Copy \`/generated-local/${project.id}/lib/schema.ts\` and \`/generated-local/${project.id}/lib/agents.ts\` into your app's \`lib/\` folder.
4. Use \`entities\` and \`agents\` as the single source of truth for schema + agent config.

> Zero17's job: give you a serious starting point in minutes.
> Your job: make it legendary.
`;

  /* ------------------------------------------------------------------------ */
  /*  Write files                                                             */
  /* ------------------------------------------------------------------------ */

  const filesWritten: string[] = [];

  async function writeFile(relPath: string, contents: string) {
    const fullPath = path.join(rootDir, relPath);
    const dir = path.dirname(fullPath);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(fullPath, contents, "utf8");
    filesWritten.push(relPath);
  }

  await writeFile("app/layout.tsx", layoutTsx);
  await writeFile("app/page.tsx", pageTsx);
  await writeFile("app/globals.css", globalsCss);
  await writeFile("lib/schema.ts", schemaTs);
  await writeFile("lib/agents.ts", agentsTs);
  await writeFile("README.md", readme);

  return {
    rootDir,
    files: filesWritten,
  };
}
